"""create user_plans table

Revision ID: 694ef2ad3878
Revises: 82fdad317010
Create Date: 2026-06-14 21:59:17.787991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694ef2ad3878'
down_revision: Union[str, Sequence[str], None] = '82fdad317010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_api_keys_hashed_key'), 'developer_api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_developer_api_keys_user_id'), 'developer_api_keys', ['user_id'], unique=False)
    op.create_table('feature_usages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_ai_chats', sa.Integer(), nullable=False),
    sa.Column('monthly_pqc_scans', sa.Integer(), nullable=False),
    sa.Column('total_compute_overhead', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_feature_usages_user_id'), 'feature_usages', ['user_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', postgresql.ENUM('FREE', 'PRO', 'ENTERPRISE', name='user_tier_enum'), nullable=False),
    sa.Column('cycle_reset_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_plans_user_id'), 'user_plans', ['user_id'], unique=False)
    op.create_table('wallet_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance_credits', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('auto_topup_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_balances_user_id'), 'wallet_balances', ['user_id'], unique=True)
    op.create_table('daily_usage_rollups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.String(length=10), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('total_shots', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['developer_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_usage_rollups_api_key_id'), 'daily_usage_rollups', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_daily_usage_rollups_usage_date'), 'daily_usage_rollups', ['usage_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_usage_rollups_usage_date'), table_name='daily_usage_rollups')
    op.drop_index(op.f('ix_daily_usage_rollups_api_key_id'), table_name='daily_usage_rollups')
    op.drop_table('daily_usage_rollups')
    op.drop_index(op.f('ix_wallet_balances_user_id'), table_name='wallet_balances')
    op.drop_table('wallet_balances')
    op.drop_index(op.f('ix_user_plans_user_id'), table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_feature_usages_user_id'), table_name='feature_usages')
    op.drop_table('feature_usages')
    op.drop_index(op.f('ix_developer_api_keys_user_id'), table_name='developer_api_keys')
    op.drop_index(op.f('ix_developer_api_keys_hashed_key'), table_name='developer_api_keys')
    op.drop_table('developer_api_keys')
    # ### end Alembic commands ###
