"""fix_production_schema

Revision ID: dff608089d6d
Revises: f77129b3393a
Create Date: 2026-05-28 14:27:10.855645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff608089d6d'
down_revision: Union[str, Sequence[str], None] = 'f77129b3393a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # Drop logtable and email_verification_tokens safely if they exist
    if 'logtable' in existing_tables:
        op.drop_index(op.f('ix_logtable_id'), table_name='logtable')
        op.drop_index(op.f('ix_logtable_level'), table_name='logtable')
        op.drop_index(op.f('ix_logtable_timestamp'), table_name='logtable')
        op.drop_table('logtable')
        
    if 'email_verification_tokens' in existing_tables:
        op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
        op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
        op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
        op.drop_table('email_verification_tokens')

    # Add last_reset_date to api_keys if not exists
    if 'api_keys' in existing_tables:
        columns = [c['name'] for c in inspector.get_columns('api_keys')]
        if 'last_reset_date' not in columns:
            op.add_column('api_keys', sa.Column('last_reset_date', sa.Date(), nullable=True))

    # Recreate usage_events index if exists
    if 'usage_events' in existing_tables:
        indexes = [idx['name'] for idx in inspector.get_indexes('usage_events')]
        if 'idx_usage_events_user_id_created_at' in indexes:
            op.drop_index('idx_usage_events_user_id_created_at', table_name='usage_events')
        op.create_index('idx_usage_events_user_id_created_at', 'usage_events', ['user_id', sa.literal_column('created_at DESC')], unique=False)

    # Modify users table safely
    if 'users' in existing_tables:
        columns = [c['name'] for c in inspector.get_columns('users')]
        if 'hashed_password' not in columns:
            op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
            if 'password' in columns:
                op.execute("UPDATE users SET hashed_password = password")
            op.alter_column('users', 'hashed_password', nullable=False)
            
        op.alter_column('users', 'role',
                   existing_type=sa.VARCHAR(),
                   type_=postgresql.ENUM('ADMIN', 'DEVELOPER', 'LEARNER', 'ENTERPRISE_USER', name='user_role_enum'),
                   existing_nullable=False)
                   
        op.alter_column('users', 'created_at',
                   existing_type=postgresql.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=False)
                   
        op.alter_column('users', 'verification_sent_at',
                   existing_type=postgresql.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=True)
                   
        op.alter_column('users', 'locked_until',
                   existing_type=postgresql.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=True)
                   
        op.alter_column('users', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=False)
                   
        indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        if 'ix_users_id' in indexes:
            op.drop_index('ix_users_id', table_name='users')
            
        if 'password' in columns:
            op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'locked_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'verification_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'DEVELOPER', 'LEARNER', 'ENTERPRISE_USER', name='user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    op.drop_index('idx_usage_events_user_id_created_at', table_name='usage_events')
    op.create_index(op.f('idx_usage_events_user_id_created_at'), 'usage_events', ['user_id', 'created_at'], unique=False)
    op.drop_column('api_keys', 'last_reset_date')
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_verification_tokens_pkey'))
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_table('logtable',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('logger_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('function', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('request_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('request_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('response_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('logtable_pkey'))
    )
    op.create_index(op.f('ix_logtable_timestamp'), 'logtable', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logtable_level'), 'logtable', ['level'], unique=False)
    op.create_index(op.f('ix_logtable_id'), 'logtable', ['id'], unique=False)
    # ### end Alembic commands ###

